name: 云端打包 APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: 设置 Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 构建 APK
        run: echo y | flet build apk --verbose --app-name "数论计算器" --app-version 1.1 --build-number 2 --icon assets/icons/app_icon.png

      - name: 上传 APK
        uses: actions/upload-artifact@v5
        with:
          name: NT-calculator-apk
          path: build/apk/*.apk
